### PR TITLE
Add custom stinger and intro for videos

### PR DESCRIPTION
**Pull request by Zaxounette**
Relates to first transition stinger and intro for videos
* Creates subfolder `Video Ressources` 
* Adds Frame by Frame folder with said frames
* Adds MKV video folder with said videos
* Adds README.md for file infos

### CODE REVIEW

**Comment by Zaxounette** [comment]
@pavlenex

**Comment by pavlenex** [comment]
Why do we need these? I have no clue how to review this, it shows as gazillion frames, maybe github is not the best platform to have these on

**Comment by pavlenex** [comment]
Also, please add generic videos that can be re-used, having v1.0.6.0 in a video is not something we can re-use.

**Comment by Zaxounette** [comment]
Then in that case I can just include the blender file for anyone to modify, and the rendered video but delete the frames that might not be useful I agree.

**Comment by pavlenex** [comment]
If you can't modify without all those frames, then the PR itself has no use, right? I can't just open this up in Blender and edit?

I suggest we close this if that's the case and you can keep them somewhere else as it really adds insane amount of weight on the entire repo for very little gain.

**Comment by Zaxounette** [comment]
You can edit with the initial Blender file.

I initially included the frame by frame because some software only use those instead of an already rendered video.


Also I'm currently rendering a reusable video of the intro, without the 1.0.6.0, will commit it in a few secondes once it's finished.

**Comment by Zaxounette** [comment]
Done.

**Comment by Zaxounette** [comment]
Scratch this PR, It'll add strain on the cloning of the repo in the long run, like Pav said.

**Pull request closed without merging**
